### ISSUE TITLE
Owncloud 8.2

### ISSUE THREAD

**Issue by rzyua** [Leryan/owncloud-decrypt#1]
Managed to decrypt files encrypted with owncoud 8.2, specifically:
$OC_Version = array(8,2,0,12);
$OC_VersionString = '8.2.0';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array(8,1);
$OC_Build = '2015-10-19T13:24:39+00:00 8ee2009de36e01a9866404f07722892f84c16e3e';

You might want to think about making the path to the data folder an optional parameter, though.

**Comment by rzyua** [comment]
BTW thanks, you saved my files after mysql crapped out on me.

**Comment by Leryan** [comment]
Glade to see it's working and it worked for you :)

I'll try to add the optional parameter for file path ASAP. If you want to send me a pull request, you're welcome too.

**Comment by Leryan** [comment]
I added `getopt()`, you may give a try if you want ;-)
